Repository unb-mds/2025-2-Lumina, pull requests merged in 2025-09, with the labels that each got.

#43 Estrutura: Cria pasta 'planejamentos' e move 'atas'
  docs/planejamentos/atas/.gitkeep
  docs/planejamentos/atas/ata_Sprint00.md
  docs/planejamentos/atas/ata_Sprint01.md
  docs/planejamentos/atas/modelo_ata.md
Labels: managemenet

#45 Fix: Move ata remanescente para a estrutura correta
  docs/planejamentos/atas/ata_Sprint02.md
Labels: managemenet

#44 Refatorando o documento de Requisitos
  docs/documentações/Requisitos.md
Labels: documentation, enhancement

#51 Colocando o diagrama na pasta certa
  docs/documentações/diagramas/diagrama de componentes.png
  docs/documentações/diagramas/diagrama de componentes.pngdiagrama de conteineres.png
  docs/documentações/diagramas/diagrama de contexto.png
Labels: documentation, enhancement, managemenet

#52 Adicionando os diagramas num formato markdown e na linguagem mermaid
  docs/documentações/diagramas/diagramas.md
Labels: documentation, enhancement

#50 Padrões de software livre
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement

#46 Criar o story map
  docs/documentações/StoryMap.md
Labels: documentation, enhancement
